---
abstract: 'manage flow of control in Continuation-Passing Style'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Fatal: 0
  Test::Identity: 0
  Test::More: 0
  Test::Refcount: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPS
provides:
  CPS:
    file: lib/CPS.pm
    version: 0.17
  CPS::Functional:
    file: lib/CPS/Functional.pm
    version: 0.17
  CPS::Future:
    file: lib/CPS/Future.pm
    version: 0.17
  CPS::Governor:
    file: lib/CPS/Governor.pm
    version: 0.17
  CPS::Governor::Deferred:
    file: lib/CPS/Governor/Deferred.pm
    version: 0.17
  CPS::Governor::Simple:
    file: lib/CPS/Governor/Simple.pm
    version: 0.17
recommends:
  Sub::Name: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.17
